# Generated by Django 5.2.3 on 2025-08-05 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(0, 0))),
                ('job_status', models.CharField(choices=[('under_inspection', 'Under Inspection'), ('inspection_completed', 'Inspection Completed'), ('parts_sourcing', 'Parts Sourcing'), ('quote_issued', 'Quote Issued'), ('pending_approval', 'Pending Approval'), ('waiting_parts', 'Waiting Parts'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('under_testing', 'Under Testing'), ('ready_washing', 'Ready for Washing'), ('ready_collection', 'Ready for Collection'), ('delivered', 'Delivered')], default='under_inspection', max_length=50)),
                ('customer_comments', models.TextField(blank=True, null=True)),
                ('workshop_comments', models.TextField(blank=True, null=True)),
                ('required_jobs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='customers.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notes', to='jobcards.jobcard')),
            ],
        ),
    ]
