# Generated by Django 5.2.3 on 2025-06-26 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='description',
            new_name='job_details',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='actual_completion',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='assigned_technician',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='estimated_completion',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='company_trn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=10),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_status',
            field=models.CharField(choices=[('under_inspection', 'Under Inspection'), ('inspection_completed', 'Inspection Completed'), ('parts_sourcing', 'Parts Sourcing'), ('quote_issued', 'Quote Issued'), ('pending_approval', 'Pending Approval'), ('waiting_parts', 'Waiting Parts'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('under_testing', 'Under Testing'), ('ready_for_washing', 'Ready for Washing'), ('ready_for_collection', 'Ready for Collection'), ('delivered', 'Delivered')], default='under_inspection', max_length=30),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='workshop_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
