# Generated by Django 5.2.3 on 2025-06-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_created_at_customer_company_name_and_more'),
        ('jobcards', '0002_rename_description_jobcard_job_details_and_more'),
        ('vehicles', '0002_alter_vehicle_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='company_trn',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicle_vin',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='job_status',
            field=models.CharField(choices=[('under_inspection', 'Under Inspection'), ('inspection_completed', 'Inspection Completed'), ('parts_sourcing', 'Parts Sourcing'), ('quote_issued', 'Quote Issued'), ('pending_approval', 'Pending Approval'), ('waiting_parts', 'Waiting Parts'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('under_testing', 'Under Testing'), ('ready_washing', 'Ready for Washing'), ('ready_collection', 'Ready for Collection'), ('delivered', 'Delivered')], default='under_inspection', max_length=30),
        ),
    ]
