# Generated by Django 5.2.3 on 2025-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_trn_customer_trn_customer_company_name_and_more'),
        ('jobcards', '0003_remove_jobcard_company_name_and_more'),
        ('vehicles', '0004_remove_vehicle_license_plate_remove_vehicle_vin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='job_details',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='job_status',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='required_jobs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcards', to='vehicles.vehicle'),
        ),
    ]
