# Generated by Django 5.2.3 on 2025-07-09 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0004_remove_jobcard_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_status',
            field=models.CharField(choices=[('under_inspection', 'Under Inspection'), ('inspection_completed', 'Inspection Completed'), ('parts_sourcing', 'Parts Sourcing'), ('quote_issued', 'Quote Issued'), ('pending_approval', 'Pending Approval'), ('waiting_parts', 'Waiting Parts'), ('work_in_progress', 'Work in Progress'), ('work_completed', 'Work Completed'), ('under_testing', 'Under Testing'), ('ready_washing', 'Ready for Washing'), ('ready_collection', 'Ready for Collection'), ('delivered', 'Delivered')], default='under_inspection', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
