# Generated by Django 5.2.3 on 2025-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_created_at_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='trn',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
