# Generated by Django 5.2.3 on 2025-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='TRN',
            new_name='trn',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
