# Generated by Django 5.2.3 on 2025-07-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_trn_customer_trn_customer_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='company',
        ),
    ]
