# Generated by Django 5.2.3 on 2025-08-05 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('plate', models.CharField(help_text='number + code + city', max_length=20, unique=True)),
                ('vin', models.CharField(blank=True, help_text='16 digits', max_length=50, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Enter current mileage in KM', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='customers.customer')),
            ],
        ),
    ]
