# Generated by Django 5.2.3 on 2025-07-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_remove_vehicle_license_plate_remove_vehicle_vin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='plate_number',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vin_number',
            new_name='vin',
        ),
    ]
