# Generated by Django 5.2.3 on 2025-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_plate_number_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
