# Generated by Django 5.2.3 on 2025-08-05 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='jobcards.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('time_required', models.FloatField(default=1.0, help_text='Estimated time in hours')),
                ('remarks', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspectionreport')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('kg', 'Kilograms'), ('g', 'Grams'), ('m', 'Meters'), ('cm', 'Centimeters')], default='pcs', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='inspections.inspectionfinding')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('required', 'Required'), ('ordered', 'Ordered'), ('in_stock', 'In Stock'), ('installed', 'Installed')], default='required', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inspections.inspectionfinding')),
            ],
        ),
    ]
