# Generated by Django 5.2.3 on 2025-07-10 14:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_jobcard_date_jobcard_job_status_jobcard_time'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name_plural': 'Quotations'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name_plural': 'Quotation Items'},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='quotation',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='jobcard',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='jobcards.jobcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
